name: Test Suite

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: '22.13.1'
  NODE_OPTIONS: '--max_old_space_size=8196'
  NX_CLOUD: false
  IGNORE_COMMIT_MESSAGE: 'chore(release): publish'

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/yarn
      - name: Fetch main branch
        run: git fetch origin main:main
      - name: Ensure workflow is associated with a pull request
        uses: ./.github/actions/validate-pr-context
      - name: Skip build from automated commit
        uses: ./.github/actions/skip-automated-commits
        with:
          ignore-commit-message: ${{ env.IGNORE_COMMIT_MESSAGE }}
      - name: Build All Packages
        run: yarn build
      - name: Run test suite on affected projects
        run: npx nx affected --target=test --parallel=4 --ci --coverage --runInBand
        env:
          JEST_JUNIT_OUTPUT_DIR: /tmp/test-results/junit
          JEST_JUNIT_ADD_FILE_ATTRIBUTE: 'true'
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: /tmp/test-results
          retention-days: 30
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.2.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Codecademy/gamut
          files: /tmp/test-results/*/lcov.info
          flags: pr-coverage
          fail_ci_if_error: false
